# Generated by Django 5.2.7 on 2025-10-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_pin_alter_employee_emp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pin',
        ),
        migrations.AddField(
            model_name='employee',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
