# Generated by Django 5.2.7 on 2025-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancelog_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_location_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
